service: amc-waiver
plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-domain-manager
  # - serverless-plugin-warmup
  - serverless-apigw-binary
  - serverless-plugin-aws-alerts
custom:
  # warmup:
  #   default:
  #     enabled: true # Whether to warm up functions by default or not
  wsgi:
    app: app.app
    packRequirements: false
  # - serverless-python-requirements
  pythonRequirements:
    dockerizePip: non-linux
  customDomain:
    domainName: amc-waiver.heychao.com
    createRoute53Record: false
  apigwBinary:
    types:
      - 'image/jpeg'
      - 'text/html'
      - 'application/zip'
      - 'multipart/form-data'
  alerts:
    definitions:  # these defaults are merged with your definitions
      functionErrors:
        period: 300 # override period
    alarms:
      - functionErrors
    topics:
      alarm:
        topic: ${env:AWS_LAMBDA_SNS_TOPIC}

package:
  exclude:
    - node_modules/**
    - venv/**
    - __pycache__/**

provider:
  name: aws
  runtime: python3.11
  memorySize: 128
  environment:
    SECRET_KEY: ${env:SECRET_KEY}
  httpApi:
    cors: true
  tracing:
    apiGateway: true
    lambda: true

functions:
  web:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}
